some pylint issues resolved
webpy/webpy pull request #740
Opened 2022-10-12 02:06 UTC by marksmayo

All tests passed afterwards as well

2022-10-12 03:32 UTC, marksmayo commented
spellchecking? frustrating as it was wrong to begin with. I'll try to fix.

2022-10-12 03:47 UTC, iredmail commented
Is file `.vscode/settings.json` necessary? `foo.py`? etc

2022-10-12 03:54 UTC, marksmayo commented
AH vscode is 'helpful' when you run tests. Thanks.

2022-10-12 06:06 UTC, cclauss requested changes
The banisment of `else` and `elif` does not sit well with me.    Did pylint _really_ recommend this?!?

2022-10-12 06:06 UTC, cclauss commented on web/application.py
>          def wsgi(env, start_resp):
Let's fix this function in a separate PR because we do not support Python 2.

2022-10-12 06:06 UTC, cclauss commented on web/browser.py
> -
Please revert and do with `isort` in a separate pr.

2022-10-12 06:06 UTC, cclauss commented on web/browser.py
> -class Browser(object):
👍

2022-10-12 06:06 UTC, cclauss commented on web/httpserver.py
> +            except Exception:
👍

2022-10-12 06:06 UTC, cclauss commented on web/session.py
> +from base64 import encodebytes, decodebytes
isort

2022-10-12 06:06 UTC, cclauss commented on web/template.py
> +from collections.abc import MutableMapping
isort

2022-10-12 19:45 UTC, marksmayo commented on .vscode/settings.json
> +}
Indeed - message R1705 - https://pheanex.github.io/pylint/

2022-10-12 19:46 UTC, marksmayo commented on tests/test_application.py
> +                raise web.seeother("/bar")
Yes - R1720 -https://vald-phoenix.github.io/pylint-errors/plerr/errors/refactoring/R1720.html

2022-10-13 07:45 UTC, cclauss commented
Please rebase and let's see what is left.  I do not use pylint because it always requires so much configuration but other maintainers may disagree.  I would definitely disable R1705 and R1720.  I use flake8 because it finds syntax errors and undefined names and it has light touch config.

2023-01-12 10:43 UTC, cclauss commented
We do not use pylint because we use flake8 instead.

2023-01-12 10:43 UTC, closed without merging